name: mattb
favicon: null
layout_spectrum: 0.8000971113797277
typography_spectrum: 0.25563188293017447
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.35908841784112155
  lightness: 0.6330060851760209
  saturation: 0.8288171703461558
  rhythmicContrast: 0.05169628723524511
purpose: []
